config/routes.rb
Rails.application.routes.draw do

  get 'guidelines/index'

  get 'pages/home'

 get 'session/new'

 root :to =>'pages#home'

 get '/login' => 'session#new'
 post '/login' =>'session#create'
 delete '/login' => 'session#destroy'
 # get '/mealplans/:date' => 'mealplans#showbydate', as: :mealplanshowbydate

# get '/mealplans/:date', to: 'mealplans#showbydate', as: :mealplanshowbydate

  resources :usercategories
  resources :servingguides
  #*********************this code is not used**********************
  #this route is given to create a link to the showbydate page which will be
  #the url of the event on the calendar.
  get '/mealplans/date/:date' => 'mealplans#showbydate', as: :mealplanshowbydate
  #*****************************************************************

  get '/nutritioncalculator' =>'servingguides#nutrition'

  get '/users/:id/activate' => 'users#activate', as: :useractivate

  resources :mealplans do
    collection do
      put :update_all
    end
  end

  resources :families
  resources :users


  # get '/mealplans/:date' => 'mealplans#showbydate', as: :mealplanshowbydate

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/family.rb
# == Schema Information
#
# Table name: families
#
#  id         :integer          not null, primary key
#  name       :text
#  address    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Family < ApplicationRecord
 has_many :users

end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  # GET /families
  # GET /families.json
  def index
    #*******************************************
    if @current_user.present?
      @families = Family.where(:id => @current_user.family_id)
      @family_user = User.where(:family_id =>@current_user.family_id )
      @mealplans_family = Mealplan.where(:user_id => @family_user.ids)
    end
    #*******************************************
    # if @current_user.present?
    #   @family_user = Users.where(:family_id => @current_user.family_id)
    # end
  end
  # GET /families/1
  # GET /families/1.json
  def show
  end
  # GET /families/new
  def new
    @family = Family.new
  end
  # GET /families/1/edit
  def edit
  end
  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: 'Family was successfully created.' }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: 'Family was successfully updated.' }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url, notice: 'Family was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.require(:family).permit(:name, :address)
    end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_form.html.erb
<%= form_with(model: family, local: true) do |form| %>
  <% if family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
      <% family.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :family_name ,:required =>true %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :family_address,:required =>true  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Editing Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<%if @current_user.nil?%>
<h2>Please <%= link_to 'Sign in', login_path %></h2>
<% elsif @current_user.present?%>
    <p id="notice"><%= notice %></p>
    <h1>My Family</h1>
        <% if @families.present? %>
              <table class = "table table-striped table-bordered">
                <thead>

                  <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @families.each do |family| %>
                    <tr>
                      <td><%= family.name %></td>
                      <td><%= family.address %></td>
                      <!-- <td><%= link_to 'Show', family %></td> -->
                      <td><%= link_to 'Edit', edit_family_path(family) %></td>
                      <!-- <td><%= link_to 'Destroy', family, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
                    </tr>
                  <% end %>
                </tbody>
              </table>
        <% else %>
          <h4>Please <%= link_to 'click here',edit_user_path(@current_user.id),:class => 'badge badge-warning'%> to join/create a family</h4>
        <% end %>

    <table class = "table familylayout">
      <tr>
        <td><h3>Family Members</h3></td>
      </tr>
      <% @family_user.each do |user| %>
      <tr>
        <td><%= user.name %></td>
      </tr>
      <% end %>
    </table>
    <br>



    <!-- Family Members Mealplans-->
    <h3>Meal history of Family Members</h3>
    <p id="notice"><%= notice %></p>
    <table id="familymealplan" class = "table table-striped table-bordered">
      <thead>
        <tr>
          <th>User</th>
          <th>Date</th>
          <th>Meal Type</th>
          <th>Veg</th>
          <th>Fruit</th>
          <th>Grain</th>
          <th>Meat</th>
          <th>Milk</th>
          <th>Additional serve</th>
        </tr>
      </thead>
        <tbody>
          <% @mealplans_family.order(:user_id).each do |mealplan1| %>
            <tr class="date-<%= mealplan1.date %>">
              <td><%= mealplan1.user.name %></td>
              <td><%= mealplan1.date %></td>
              <td><%= mealplan1.mealtype %></td>
              <td><%= mealplan1.veg %></td>
              <td><%= mealplan1.fruit %></td>
              <td><%= mealplan1.grain %></td>
              <td><%= mealplan1.meat %></td>
              <td><%= mealplan1.milk %></td>
              <td><%= mealplan1.additional_serve %></td>
              <!-- <td><%= link_to 'View Graph', mealplanshowbydate_path(mealplan1.date)%></td> -->
          <% end %>
        </tbody>
    </table>

<% end %>

app/views/families/new.html.erb
<h1>New Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Back', families_path %>

app/views/families/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @family.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @family.address %>
</p>

<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %>