config/routes.rb
Rails.application.routes.draw do

  get 'guidelines/index'

  get 'pages/home'

 get 'session/new'

 root :to =>'pages#home'

 get '/login' => 'session#new'
 post '/login' =>'session#create'
 delete '/login' => 'session#destroy'
 # get '/mealplans/:date' => 'mealplans#showbydate', as: :mealplanshowbydate

# get '/mealplans/:date', to: 'mealplans#showbydate', as: :mealplanshowbydate

  resources :usercategories
  resources :servingguides
  #*********************this code is not used**********************
  #this route is given to create a link to the showbydate page which will be
  #the url of the event on the calendar.
  get '/mealplans/date/:date' => 'mealplans#showbydate', as: :mealplanshowbydate
  #*****************************************************************

  get '/nutritioncalculator' =>'servingguides#nutrition'

  get '/users/:id/activate' => 'users#activate', as: :useractivate

  resources :mealplans do
    collection do
      put :update_all
    end
  end

  resources :families
  resources :users


  # get '/mealplans/:date' => 'mealplans#showbydate', as: :mealplanshowbydate

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :text
#  password_digest :string
#  usercategory_id :integer
#  dob             :date
#  email           :text
#  family_id       :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_type       :text
#

class User < ApplicationRecord
  has_secure_password
  belongs_to :family, :optional => true
  has_many :mealplans
  belongs_to :usercategory, :optional =>true
  validates :email, :presence =>true, :uniqueness =>true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

   @users = User.all

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
#line below will send welcome email to the user
      # UserMailer.welcome(@user).deliver_now
      redirect_to login_path
    else
      render :new
    end
  end



  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update user_params # user.save, all in one step. update and saves.
    redirect_to @user
    else
      render :edit #using this data in the update action, render edit page.
    end
  end

  def show
    @user = User.find params[:id]
  end

  # def activate
  #   @user = User.find params[:id]
  #   User.where(:id => params[:id]).update(activated: 't')
  #     redirect_to login_path
  # end

  private
    def user_params
      params.require(:user).permit(:id, :name, :password, :password_confirmation, :usercategory_id, :dob, :email, :family_id,:user_type,:activated)

    end







  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  #
  # # GET /users
  # # GET /users.json
  # def index
  #   @users = User.all
  # end
  #
  # # GET /users/1
  # # GET /users/1.json
  # def show
  # end
  #
  # # GET /users/new
  # def new
  #   @user = User.new
  # end
  #
  # # GET /users/1/edit
  # def edit
  # end
  #
  # # POST /users
  # # POST /users.json
  # def create
  #   @user = User.new(user_params)
  #
  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /users/1
  # # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
  #
  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_user
  #     @user = User.find(params[:id])
  #   end
  #
  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def user_params
  #     params.require(:user).permit(:name, :password_digest, :usercategory_id, :dob, :email, :family_id)
  #   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :user_name %>
  </div>

  <!-- <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest, id: :user_password_digest %>
  </div> -->


  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password, :required =>true %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password, :required =>true %>
  </div>

  <div class="field">
    <%= form.label :usercategory_id %>
    <%= form.select :usercategory_id, Usercategory.pluck(:category,:id), {:include_blank => '<----- Select Category ----->' }, :required => true%>

  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select :dob, id: :user_dob ,start_year:1950,end_year: Date.today.year%>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email,:required =>true %>
  </div>


  <% if @current_user.present? %>
  <div class="field">
    <%= form.label :family_id %>
    <%= form.select :family_id, Family.pluck(:name,:id), {:include_blank => '<----- Select FamilyName ----->' }, :required => true%>
    <p>Don't find your family?</p>
    <p><%= link_to 'Click here',new_family_path ,:class => 'badge badge-warning graph'%> to create your family</p>


  </div>
  <% end %>

  <%= form.hidden_field(:user_type, {:value => 'user'}) %>
  <%= form.hidden_field(:activated, {:value => 't'}) %>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if @current_user.present? && @current_user.user_type == 'Admin'%>
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class = "indexlayout">
  <thead>
    <tr>
      <th style="width:10%">Name</th>
      <th style="width:10%">User type</th>
      <th style="width:10%">Usercategory</th>
      <th style="width:10%">Dob</th>
      <th style="width:10%">Email</th>
      <th style="width:10%">Family</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td style="width:10%"><%= user.name %></td>
        <td style="width:10%"><%= user.user_type %></td>
        <td style="width:10%"><%= user.usercategory_id %></td>
        <td style="width:10%"><%= user.dob %></td>
        <td style="width:10%"><%= user.email %></td>
        <td style="width:10%"><%= user.family_id %></td>

        <td style="width:10%"><%= link_to 'Show', user,:class => 'badge badge-warning graph' %></td>
        <td style="width:10%"><%= link_to 'Edit', edit_user_path(user) ,:class => 'badge badge-warning graph'%></td>
        <td style="width:10%"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' },:class => 'badge badge-warning graph' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

<% end %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<table class ="table layout" align = "center">
  <p id="notice"><%= notice %></p>

  <tr>
  <td>Name</td>
    <td><%= @user.name %></td>
  </tr>

  <tr>
    <td>Usercategory</td>
    <td><%= @user.usercategory.category %></td>
  </tr>
  <tr>
    <td>Date of birth</td>
    <td><%= @user.dob %></td>
  </tr>

  <tr>
    <td>Email</td>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <td>Family</td>
    <td><%= @user.family.name%></td>
  </tr>

  <tr><td colspan = "2"><%= link_to 'Edit', edit_user_path(@user),:class => 'badge badge-warning graph' %></td></tr>
  <!-- <%= link_to 'Back', users_path %> -->

</table>