config/routes.rb
Rails.application.routes.draw do

  get 'guidelines/index'

  get 'pages/home'

 get 'session/new'

 root :to =>'pages#home'

 get '/login' => 'session#new'
 post '/login' =>'session#create'
 delete '/login' => 'session#destroy'
 # get '/mealplans/:date' => 'mealplans#showbydate', as: :mealplanshowbydate

# get '/mealplans/:date', to: 'mealplans#showbydate', as: :mealplanshowbydate

  resources :usercategories
  resources :servingguides
  #*********************this code is not used**********************
  #this route is given to create a link to the showbydate page which will be
  #the url of the event on the calendar.
  get '/mealplans/date/:date' => 'mealplans#showbydate', as: :mealplanshowbydate
  #*****************************************************************

  get '/nutritioncalculator' =>'servingguides#nutrition'

  get '/users/:id/activate' => 'users#activate', as: :useractivate

  resources :mealplans do
    collection do
      put :update_all
    end
  end

  resources :families
  resources :users


  # get '/mealplans/:date' => 'mealplans#showbydate', as: :mealplanshowbydate

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mealplan.rb
# == Schema Information
#
# Table name: mealplans
#
#  id               :integer          not null, primary key
#  user_id          :integer
#  date             :date
#  mealtype         :text
#  veg              :integer
#  fruit            :integer
#  grain            :integer
#  meat             :integer
#  milk             :integer
#  additional_serve :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Mealplan < ApplicationRecord
  belongs_to :user

end

app/controllers/mealplans_controller.rb
class MealplansController < ApplicationController
  # before_action :set_mealplan, only: [:show, :edit, :update, :destroy]

  # GET /mealplans
  # GET /mealplans.json
  def index
    if @current_user.present?
    @mealplans = Mealplan.all
        @mealplan_user = Mealplan.where(:user_id => @current_user.id)
    # @servingguide_test = Servingguide.where(:usercategory_id => @current_user.usercategory_id, :age => Date.today.year - @current_user.dob.year)
    @servingguide = Servingguide.where("usercategory_id = ? and age < ?",  @current_user.usercategory_id ,Date.today.year - @current_user.dob.year )
  end


  end

  # GET /mealplans/1
  # GET /mealplans/1.json

  def update_all

    params['mealplan'].keys.each do |id|
      @mealplan = Mealplan.find(id.to_i)
      @mealplan.update_attributes(mealplan_params(id))
    end
  # Mealplan.update_all({veg: 4},{id: params[:id]})
  redirect_to(mealplans_url)
  # redirect_to(new_mealplan_path)
  end

  def show
    # cant search by date bcos its always by id..so create new def showby date
    @mealplan = Mealplan.find(params[:id])
  end


  def showbydate
    if @current_user.present?
    @mealplan_showbydate = Mealplan.where("user_id = ? and date = ?", @current_user.id, params[:date])
    @servingguide = Servingguide.where("usercategory_id = ? and age < ?",  @current_user.usercategory_id ,Date.today.year - @current_user.dob.year )
  end
  end



  # GET /mealplans/new
  def new
    # @mealplan = Mealplan.new
    # ******************************
    @servingguide = Servingguide.where("usercategory_id = ? and age < ?",  @current_user.usercategory_id ,Date.today.year - @current_user.dob.year )

  if Mealplan.where("user_id = ? and date = ?",  @current_user.id ,Date.today).present?
      @mealplans = Mealplan.where("user_id = ? and date = ?",  @current_user.id ,Date.today)
  else
      Mealplan.create :user_id => @current_user.id, :date => Date.today , :mealtype => 'Breakfast'
      Mealplan.create :user_id => @current_user.id, :date => Date.today , :mealtype => 'Lunch'
      Mealplan.create :user_id => @current_user.id, :date => Date.today , :mealtype => 'Snack'
      Mealplan.create :user_id => @current_user.id, :date => Date.today , :mealtype => 'Dinner'
      @mealplans = Mealplan.where("user_id = ? and date = ?",  @current_user.id ,Date.today)
  end
  @vegtotal = Mealplan.where("user_id = ? and date = ?",  @current_user.id ,Date.today).sum(:veg)
  @fruittotal = Mealplan.where("user_id = ? and date = ?",  @current_user.id ,Date.today).sum(:fruit)
  @graintotal = Mealplan.where("user_id = ? and date = ?",  @current_user.id ,Date.today).sum(:grain)
  @meattotal = Mealplan.where("user_id = ? and date = ?",  @current_user.id ,Date.today).sum(:meat)
  @milktotal = Mealplan.where("user_id = ? and date = ?",  @current_user.id ,Date.today).sum(:milk)
  @addltotal = Mealplan.where("user_id = ? and date = ?",  @current_user.id ,Date.today).sum(:additional_serve)

    # ******************************
  end

  # GET /mealplans/1/edit
  def edit
    # ******************************
    @mealplans = Mealplan.all
    # ******************************
  end

  # POST /mealplans
  # POST /mealplans.json
  def create
    @mealplan = Mealplan.new(mealplan_params)

    respond_to do |format|
      if @mealplan.save
        format.html { redirect_to @mealplan, notice: 'Mealplan was successfully created.' }
        format.json { render :show, status: :created, location: @mealplan }
      else
        format.html { render :new }
        format.json { render json: @mealplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mealplans/1
  # PATCH/PUT /mealplans/1.json
  def update
    @mealplan = Mealplan.find(params[:id])
    respond_to do |format|
      if @mealplan.update(mealplan_params)
        format.html { redirect_to @mealplan, notice: 'Mealplan was successfully updated.' }
        format.json { render :show, status: :ok, location: @mealplan}
      else
        format.html { render :edit }
        format.json { render json: @mealplan.errors, status: :unprocessable_entity }
      end
    end
  end




  # DELETE /mealplans/1
  # DELETE /mealplans/1.json
  def destroy
    @mealplan = Mealplan.find(params[:id])
    @mealplan.destroy
    respond_to do |format|
      format.html { redirect_to mealplans_url, notice: 'Mealplan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_mealplan
    #   @mealplan = Mealplan.find(params[:id])
    #
    #
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def mealplan_params
    #   params.require(:mealplan).permit(:user_id, :date, :mealtype, :veg, :fruit, :grain, :meat, :milk, :additional_serve)
    # end

    def mealplan_params(id)
       params.require(:mealplan).fetch(id).permit(:user_id, :date, :mealtype, :veg, :fruit, :grain, :meat, :milk, :additional_serve)

     end

end

app/helpers/mealplans_helper.rb
module MealplansHelper
end

app/views/mealplans/_form.html.erb
<%if @current_user.nil?%>

<h2>Please <%= link_to 'Sign in', login_path %></h2>

<% elsif @current_user.present?%>

<p id="notice"><%= notice %></p>

<h1>Meal intake of the day</h1>
<%= form_for :mealplan, :url => update_all_mealplans_path, :html => { :method => :put } do %>

<table class="table table-bordered">
  <thead>
    <% @servingguide.each do |servingguide| %>

        <tr>
          <th width = '10%'>Date</th>
          <th>Meal</th>
          <th>Vegetables & legumes/beans</th>
          <th>Fruit</th>
          <th>Grain (cereal) foods, mostly wholegrain</th>
          <th>Lean meat and poultry, fish, eggs, nuts and seeds, and legumes/beans</th>
          <th>Milk, yoghurt, cheese and/or alternatives (mostly reduced fat)</th>
          <th>Approx. number of additional serves from the five food groups or discretionary choices</th>
        </tr>

        <tr>
          <td colspan = "2">Recommended daily serving size</td>
          <td><%= servingguide.veg %></td>
          <td id="Fruit"><%= servingguide.fruit %></td>
          <td id="Grain"><%= servingguide.grain %></td>
          <td id="Meat"><%= servingguide.meat %></td>
          <td id="Milk"><%= servingguide.milk %></td>
          <td id="AddlServe"><%= servingguide.additional_serve %></td>
        </tr>
      <% end %>
      <tr>
        <th colspan = "8">Enter the Serving size for each food type</th>
      </tr>

  </thead>

  <tbody>

    <tr>
      <td colspan='2'>Samples of what constitutes 1 serve in each food type</td>
      <td>1/2 cup cooked vegetables (broccoli, carrots, etc.). 1/2 cup cooked beans, peas or lentils. 1 cup raw salad vegetables. 1/2 cup sweet corn. </td>
      <td>1 medium apple, banana, orange or pear. 2 small apricots, kiwi fruits or plums.</td>
      <td>1 slice bread. 1/2 cup cooked rice, pasta, noodles etc. 1/2 cup cooked porridge. 1 small muffin or scone.</td>
      <td>65g cooked lean red meat. 80g cooked chicken or turkey. 2 large eggs. 1 cup chick peas. </td>
      <td>1 cup milk. 2 slices of cheddar cheese. 3/4 cup yoghurt.</td>
      <td></td>
    </tr>
    <% @mealplans.order(:created_at).each do |mealplan| %>
      <%= fields_for "mealplan[]", mealplan do |mealplan_fields| %>
        <tr>
          <td><%= mealplan.date %></td>
          <td><%= mealplan.mealtype %></td>
          <td><%= mealplan_fields.text_field :veg ,size: 3%></td>
          <td><%= mealplan_fields.text_field :fruit,size: 3 %></td>
          <td><%= mealplan_fields.text_field :grain,size: 3%></td>
          <td><%= mealplan_fields.text_field :meat,size: 3 %></td>
          <td><%= mealplan_fields.text_field :milk,size: 3%></td>
          <td><%= mealplan_fields.text_field :additional_serve,size: 3 %></td>
        </tr>
      <% end %>
    <% end %>
    <tr>
      <th colspan = "2">Totals for today:</th>
      <th><%= @vegtotal %></th>
      <th id="Fruit"><%= @fruittotal %></th>
      <th id="Grain"><%= @graintotal %></th>
      <th id="Meat"><%= @meattotal %></th>
      <th id="Milk"><%= @milktotal %></th>
      <th id="AddlServe"><%= @addltotal %></th>
    </tr>
  </tbody>
</table>


<div class="actions">
    <%= submit_tag %>
  </div>
  <% end %>
<br>

<% end %>

app/views/mealplans/edit.html.erb
<h1>Editing Mealplan</h1>

<%= render 'form', mealplan: @mealplan %>

<%= link_to 'Show', @mealplan %> |
<%= link_to 'Back', mealplans_path %>

app/views/mealplans/extra_barchart.html.erb
<!-- <table id="mealchart">
  <thead>

         <tr>
             <th></th>
             <th>Recommended</th>
             <th>Eaten</th>
         </tr>
     </thead>
     <tbody>
         <tr>
             <th>Vegetables</th>
             <td id = "ServingVeg"><%= @servingguide.first.veg %></td>
             <td id = "GraphVeg"><%= @mealplans.sum(:veg) %></td>
         </tr>
         <tr>
             <th>Fruit</th>
             <td><%= @servingguide.first.fruit %></td>
             <td id = "GraphFruit"><%= @mealplans.sum(:fruit) %></td>
         </tr>
         <tr>
             <th>Grain</th>
             <td><%= @servingguide.first.grain %></td>
             <td id = "GraphGrain"><%= @mealplans.sum(:grain) %></td>
         </tr>
         <tr>
             <th>Meat</th>
             <td><%= @servingguide.first.meat %></td>
             <td id = "GraphMeat"><%= @mealplans.sum(:meat) %></td>
         </tr>
         <tr>
             <th>Milk</th>
             <td><%= @servingguide.first.milk %></td>
             <td id = "GraphMilk"><%= @mealplans.sum(:milk) %></td>
         </tr>
         <tr>
             <th>AddlServe</th>
             <td><%= @servingguide.first.additional_serve %></td>
             <td id = "GraphAddlServe"><%= @mealplans.sum(:additional_serve) %></td>
         </tr>
     </tbody>

  </table>
<div id="container2" style="width:100%; height:400px;"></div> -->

app/views/mealplans/index.html.erb
<!-- <script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
 -->


<%if @current_user.nil?%>

<h2>Please <%= link_to 'Sign in', login_path,:class => 'badge badge-warning' %></h2>

<% elsif @current_user.present?%>

<p id="notice"><%= notice %></p>

<h2><%= link_to "Today's meal plan", new_mealplan_path,:class => 'badge badge-warning' %></h2>

<div id="calendar">
</div>
<p></p>
<p></p>
<table id="mealplans" class = "table table-bordered">
  <thead>
        <tr>
          <th>Date</th>
          <th>Mealtype</th>
          <th>Veg</th>
          <th>Fruit</th>
          <th>Grain</th>
          <th>Meat</th>
          <th>Milk</th>
          <th>Additional serve</th>
          <th>Graph</th>
        </tr>
      <% @servingguide.each do |servingguide| %>
        <tr>
          <th colspan = "2">Recommended daily serving size</th>
          <th><%= servingguide.veg %></th>
          <th id="Fruit"><%= servingguide.fruit %></th>
          <th id="Grain"><%= servingguide.grain %></th>
          <th id="Meat"><%= servingguide.meat %></th>
          <th id="Milk"><%= servingguide.milk %></th>
          <th id="AddlServe"><%= servingguide.additional_serve %></th>
          <th></th>
        </tr>
      <% end %>
    </thead>
    <tbody>
      <% @mealplan_user.each do |mealplan| %>
        <tr class="date-<%= mealplan.date %>">
          <td><%= mealplan.date %></td>
          <td><%= mealplan.mealtype %></td>
          <td><%= mealplan.veg %></td>
          <td><%= mealplan.fruit %></td>
          <td><%= mealplan.grain %></td>
          <td><%= mealplan.meat %></td>
          <td><%= mealplan.milk %></td>
          <td><%= mealplan.additional_serve %></td>
          <td><%= link_to 'View Graph', mealplanshowbydate_path(mealplan.date),:class => 'badge badge-warning graph'%></td>
        </tr>
      <% end %>

    </tbody>
</table>
<br>
<% end %>

app/views/mealplans/new.html.erb
<%= render 'form', mealplan: @mealplan %>

<%= link_to 'Mealplan History', mealplans_path %>

app/views/mealplans/show.html.erb
<!-- <p id="notice"><%= notice %></p>
<p>
  <strong>User:</strong>
  <%= @mealplan.user_id %>
</p>
<p>
  <strong>Date:</strong>
  <%= @mealplan.date %>
</p>
<p>
  <strong>Mealtype:</strong>
  <%= @mealplan.mealtype %>
</p>
<p>
  <strong>Veg:</strong>
  <%= @mealplan.veg %>
</p>
<p>
  <strong>Fruit:</strong>
  <%= @mealplan.fruit %>
</p>
<p>
  <strong>Grain:</strong>
  <%= @mealplan.grain %>
</p>
<p>
  <strong>Meat:</strong>
  <%= @mealplan.meat %>
</p>
<p>
  <strong>Milk:</strong>
  <%= @mealplan.milk %>
</p>
<p>
  <strong>Additional serve:</strong>
  <%= @mealplan.additional_serve %>
</p>
<%= link_to 'Edit', edit_mealplan_path(@mealplan) %> |
<%= link_to 'Back', mealplans_path %> -->

app/views/mealplans/showbydate.html.erb
<!-- <script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script> -->

<%if @current_user.nil?%>

<h2>Please <%= link_to 'Sign in', login_path %></h2>

<% elsif @current_user.present?%>

    <p id="notice"><%= notice %></p>

    <h1>Mealplans</h1>

    <table class = "table table-striped table-bordered">
      <thead>
        <tr>
          <th>Date</th>
          <th>Mealtype</th>
          <th>Veg</th>
          <th>Fruit</th>
          <th>Grain</th>
          <th>Meat</th>
          <th>Milk</th>
          <th>Additional serve</th>
        </tr>
      </thead>

      <tbody>
        <% @mealplan_showbydate.each do |mealplan| %>
          <tr>
            <td><%= mealplan.date %></td>
            <td><%= mealplan.mealtype %></td>
            <td><%= mealplan.veg %></td>
            <td><%= mealplan.fruit %></td>
            <td><%= mealplan.grain %></td>
            <td><%= mealplan.meat %></td>
            <td><%= mealplan.milk %></td>
            <td><%= mealplan.additional_serve %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <div id="container2" style="width:100%; height:400px;"></div>


    <p></p>

    <table id="mealchart" class = "table table-striped table-bordered">
      <thead>

             <tr>
                 <th></th>
                 <th>Recommended</th>
                 <th>Eaten</th>
             </tr>
         </thead>
         <tbody>
             <tr>
                 <th>Vegetables</th>
                 <td id = "ServingVeg"><%= @servingguide.first.veg %></td>
                 <td id = "GraphVeg"><%= @mealplan_showbydate.sum(:veg) %></td>
             </tr>
             <tr>
                 <th>Fruit</th>
                 <td><%= @servingguide.first.fruit %></td>
                 <td id = "GraphFruit"><%= @mealplan_showbydate.sum(:fruit) %></td>
             </tr>
             <tr>
                 <th>Grain</th>
                 <td><%= @servingguide.first.grain %></td>
                 <td id = "GraphGrain"><%= @mealplan_showbydate.sum(:grain) %></td>
             </tr>
             <tr>
                 <th>Meat</th>
                 <td><%= @servingguide.first.meat %></td>
                 <td id = "GraphMeat"><%= @mealplan_showbydate.sum(:meat) %></td>
             </tr>
             <tr>
                 <th>Milk</th>
                 <td><%= @servingguide.first.milk %></td>
                 <td id = "GraphMilk"><%= @mealplan_showbydate.sum(:milk) %></td>
             </tr>
             <tr>
                 <th>AddlServe</th>
                 <td><%= @servingguide.first.additional_serve %></td>
                 <td id = "GraphAddlServe"><%= @mealplan_showbydate.sum(:additional_serve) %></td>
             </tr>
         </tbody>

      </table>

  <br><br>
<% end %>