config/routes.rb
Rails.application.routes.draw do

  get 'guidelines/index'

  get 'pages/home'

 get 'session/new'

 root :to =>'pages#home'

 get '/login' => 'session#new'
 post '/login' =>'session#create'
 delete '/login' => 'session#destroy'
 # get '/mealplans/:date' => 'mealplans#showbydate', as: :mealplanshowbydate

# get '/mealplans/:date', to: 'mealplans#showbydate', as: :mealplanshowbydate

  resources :usercategories
  resources :servingguides
  #*********************this code is not used**********************
  #this route is given to create a link to the showbydate page which will be
  #the url of the event on the calendar.
  get '/mealplans/date/:date' => 'mealplans#showbydate', as: :mealplanshowbydate
  #*****************************************************************

  get '/nutritioncalculator' =>'servingguides#nutrition'

  get '/users/:id/activate' => 'users#activate', as: :useractivate

  resources :mealplans do
    collection do
      put :update_all
    end
  end

  resources :families
  resources :users


  # get '/mealplans/:date' => 'mealplans#showbydate', as: :mealplanshowbydate

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="header">
        <%= image_tag "logo.jpg" , :class =>'logo'%>
        <%= image_tag "logo-name.png" , :class =>'logoname'%>

      </div>

      <div class = "text-right navigation">
        <% if @current_user.present? %>
        <%= link_to "Sign Out #{@current_user.name}",login_path, :method => 'delete'%>
        <% else %>
        <%= link_to 'Sign Up', new_user_path %>
        <%= link_to 'Sign in',login_path %>
        <% end %>
      </div>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
          <%if @current_user.present? && @current_user.user_type == 'admin' %>
          <%= link_to 'Home',root_path, :class => 'nav-item nav-link change' %>
          <%= link_to 'UserCategory',usercategories_path, :class => 'nav-item nav-link' %>
          <%= link_to 'Serving Guide',servingguides_path, :class => 'nav-item nav-link' %>
          <%= link_to 'MealPlan', mealplans_path, :class => 'nav-item nav-link' %>
          <%= link_to 'Family', families_path, :class => 'nav-item nav-link' %>
          <%= link_to 'Guidelines', guidelines_index_path, :class => 'nav-item nav-link'  %>
          <%= link_to 'Nutrition Finder',nutritioncalculator_path, :class => 'nav-item nav-link' %>

          <% else %>
          <%= link_to 'Home',root_path, :class => 'nav-item nav-link' %>
          <%= link_to 'Serving Guide',servingguides_path, :class => 'nav-item nav-link' %>
          <%= link_to 'MealPlan', mealplans_path, :class => 'nav-item nav-link' %>
          <%= link_to 'Family', families_path, :class => 'nav-item nav-link' %>
          <%= link_to 'Guidelines', guidelines_index_path, :class => 'nav-item nav-link'  %>
          <%= link_to 'Nutrition Finder',nutritioncalculator_path, :class => 'nav-item nav-link' %>
          <% end %>
          <% if @current_user.present? %>
          <%= link_to 'Edit Profile',edit_user_path(@current_user.id), :class => 'nav-item nav-link'  %>
          <% end %>
        </div>
      </div>
    </nav>

    </header>


    <main>
      <div class="content">
        <%= yield %>

      </div>

    </main>
  </div>
  <footer class = "text-center footer">Created by Meena</footer>

  </body>
</html>